console.log("Hello my name is Prakhar Mishra") ; 
var webpage = "First Webpage On VS Code" ; 
console.log(webpage); 
var firstname = "Prakhar" ; 
var lastname = "Mishra"; 
console.log(firstname);
console.log(lastname);
var fullname = firstname.concat(lastname);
console.log(fullname);
var length_of_the_name = fullname.length;
console.log(length_of_the_name);
var name1 = "Amit";
console.log(name1);
var replace_name = name1.replace("Amit","Prakhar");
console.log(replace_name);
var capital_name = "PRAKHAR" ; 
var lower_name =capital_name.toLowerCase();
console.log(lower_name); 
var lower_case = "vibha";
var Upper_case= lower_case.toUpperCase();
console.log(Upper_case);
var square_root = Math.sqrt(64);
console.log(square_root);
var max_number = Math.max(1,780);
console.log(max_number);
var min_number = Math.min(1,789);
console.log(min_number);
var power = Math.pow(2,4);
console.log(power);